language: cpp
os:
    - linux
before_install:
    - sudo apt-get install cmake
    - wget http://bitbucket.org/eigen/eigen/get/3.2.4.tar.bz2
    - tar xjf 3.2.4.tar.bz2
    - #
    - cd eigen-eigen-10219c95fe65
    - mkdir build
    - cd build
    - cmake ..
    - sudo make install
    - cd ../..
    - rm -rf eigen-eigen-10219c95fe65 3.2.4.tar.bz2
    - #
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
    - sudo apt-get update
    - sudo apt-get install clang
    - sudo apt-get install zlib1g-dev
    - #
    - wget https://github.com/gflags/gflags/archive/master.zip
    - unzip master.zip
    - cd gflags-master
    - mkdir build && cd build
    - export CXXFLAGS="-fPIC" && cmake .. && make VERBOSE=1
    - make
    - sudo make install
    - cd ../../
    - rm -rf master.zip && gflags-master
    - #
    - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip
    - cd gtest-1.7.0
    - mkdir mybuild
    - cd mybuild
    - cmake ..
    - make -j 9
    - cp libgtest_main.a /usr/local/lib/libgtest_main.a
    - cp libgtest.a /usr/local/lib/libgtest.a
    - cp -R ../include/* /usr/local/include/
    - cd ../..
    - rm -rf gtest-1.7.0
compiler:
    - clang
    - gcc
script:
    - scripts/travis_tests.sh
notifications:
    recipients:
        - szymon.sidor@gmail.com
    email:
        on_success: change
        on_failure: always
