language: cpp
os:
    - linux
sudo: required
dist: trusty
compiler:
    - gcc
before_install:
    - source scripts/ubuntu_trusty_install_cuda.sh
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install git -y
    - sudo apt-get install cmake -y
    - sudo apt-get install gcc -y
    - sudo apt-get install zlib1g-dev -y
    - sudo apt-get install libgflags2 libgflags-dev -y
    - sudo apt-get install build-essential -y
    - sudo apt-get install libblas-dev -y
    - sudo apt-get install gcc-4.9 g++-4.9 cpp-4.9 -y
    - sudo apt-get install libgtest-dev
    - pushd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/lib/
    - popd
script:
    - mkdir build
    - cd build
    - CC=gcc-4.9 CXX=g++-4.9 cmake ..
    - make -j9 dali
    - # make -j9 run_tests
matrix:
    env:
        - WITH_CUDA=FALSE
        - WITH_CUDA=TRUE CUDA=6.5-14
        - WITH_CUDA=TRUE CUDA=7.0-28
        - WITH_CUDA=TRUE CUDA=7.5-18
notifications:
    email:
        recipients:
            - szymon.sidor@gmail.com
        on_success: change
        on_failure: always
    slack:
        secure: IGmNrwpfBlZN9MuLyo6QnBZ3AKff3vuNKjDejtF4CyJbLxndynszA+HyXj9PuUiavIS3fTrDxfUs/t/e0CNnBU9zKvq0tpdCtn4MzRCxq0srNxDS0fCqKYW9NGw4wMlvHk6O2k6357KTddouaBrbMpWW7j8Zt7/6z+23bPES/itUA5/2H3JlhA9M9daArjIbmZmaYlkAY+0qVCgv3z3vta9e++GAY7XrJxuhTnSkkM+4QWXvGTXzNyVPfXmq3OsIVZGF6ze3nDwg9hmUZpglLuowsZO8bvWr/LF5G7GfhiWhuxsh1kYveocY1PNdO5g+aUO5BBvcQWT/RcczCRDeCt0DnxASj1KhAcPFzpe6uPLE28lP1o9g+kIGoKgru+/YyenTatbMHHFDI6fOKv0oJ/kGOffkZJFFT35/riAATqHoIhI8BhyuHUkyzoCLC/jMa342l4lp2FAhInkOZs88Dls9d0WWHl4tJE1YrqwuknMev7l1PANCM+kD5EmzAHUA3hhYq5qWbnu8a73fVx8s1BcpoyAF6MrWAK6swANUhxBQ5Nz5mBSsn77l9aftmPAo1F4xGF1enY+hz2mBu9ElEYee0GhVfSJSujZxaY4vBDdohD67CgYLHoUjQGnkJIsqvU8ig18cg3dZWNjiC7lL1xsyg2Ihw/WdEduzNwhZOfg=
