language: cpp
os:
    - linux
sudo: required
dist: trusty
compiler:
    - gcc
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install git -y
    - sudo apt-get install cmake -y
    - sudo apt-get install gcc -y
    - sudo apt-get install zlib1g-dev -y
    - sudo apt-get install libgflags2 libgflags-dev -y
    - sudo apt-get install build-essential -y
    - sudo apt-get install libblas-dev -y
    - sudo apt-get install gcc-4.9 g++-4.9 cpp-4.9 -y
    - sudo apt-get install libgtest-dev
    - pushd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libg* /usr/lib/
    - popd
script:
    - mkdir build
    - cd build
    - CC=gcc-4.9 CXX=g++-4.9 cmake ..
    - make -j9 dali
    - make -j9 run_tests
notifications:
    email:
        recipients:
            - szymon.sidor@gmail.com
        on_success: change
        on_failure: always
